version: "3"
services:
  app:
    container_name: emtech_jupyter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    ports:
      - 8900:8888
    command: jupyter notebook --ip=0.0.0.0 --port 8888 --allow-root --notebook-dir=/code --no-browser --NotebookApp.token=''
    restart: always
